fix: add arrow-buffer to arrow-expression feature (#332)
When running cargo-publish the delta_kernel crate failed to compile;
needed to add `arrow-buffer` to `arrow-expression` feature.
```
error[E0432]: unresolved import `arrow_buffer`
  --> src/engine/arrow_expression.rs:13:5
   |
13 | use arrow_buffer::OffsetBuffer;
   |     ^^^^^^^^^^^^ use of undeclared crate or module `arrow_buffer`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `delta_kernel` (lib) due to 1 previous error
```