fix: make Map arrow type consistent with Map parquet type (#299)
When we read parquet Map types in delta-rs, the data gets read as
rootname "key_value" and then the struct type has two fields "key",
"value". We have casting logic that expects this schema, however when we
convert our snapshot.schema to an arrow schema, a mismatch happens
because kernel is using other field names.

Error when we optimize tables with Map types.
```python
SchemaMismatchError: Could not find column keys
```

Theoretically arrow fields can use whatever names they want, but since
we are reading parquet data and therefore getting these RecordBatches
with that structure, it would be just much easier to keep the structure
of the datatypes consistent between the two.

See parquet docs:

https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps